pretrained_model_name_or_path = "E:/AI-Image/ComfyUI_windows_portable_nvidia_cu121_or_cpu/ComfyUI_windows_portable/ComfyUI/models/checkpoints/MyAnimeModel.ckpt"
vae = "E:/AI-Image/ComfyUI_windows_portable_nvidia_cu121_or_cpu/ComfyUI_windows_portable/ComfyUI/models/vae/MyAnimeModelVAE.pt"
v2 = false
train_data_dir = "E:/AI-Image/LoRa-training/LoRAmodels/Rewrite-school-uniform/RewriteUniformLoRA/image/115_RewriteUni/5_zkz"
reg_data_dir = "E:/AI-Image/LoRa-training/LoRAmodels/Rewrite-school-uniform/RewriteUniformLoRA/image/115_RewriteUni/5_zkz"
prior_loss_weight = 1
resolution = "512,512"
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 1024
bucket_reso_steps = 64
output_name = "RewriteUniLoRA"
output_dir = "E:/AI-Image/LoRa-training/LoRAmodels/Rewrite-school-uniform/RewriteUniformLoRA/model"
save_model_as = "safetensors"
save_precision = "fp16"
save_every_n_epochs = 2
max_train_epochs = 50
train_batch_size = 2
gradient_checkpointing = false
network_train_unet_only = false
network_train_text_encoder_only = false
learning_rate = 0.0005
unet_lr = 0.0001
text_encoder_lr = 1e-5
lr_scheduler = "cosine_with_restarts"
lr_warmup_steps = 0
lr_scheduler_num_cycles = 1
optimizer_type = "AdamW8bit"
network_module = "networks.lora"
network_dim = 64
network_alpha = 32
log_with = "tensorboard"
logging_dir = "./logs"
caption_extension = ".txt"
shuffle_caption = true
keep_tokens = 0
max_token_length = 255
seed = 1337
clip_skip = 2
mixed_precision = "fp16"
xformers = true
lowram = false
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = false
cache_text_encoder_outputs_to_disk = false
persistent_data_loader_workers = true
